### PR TITLE
Implement Register functions (add controller and route)

### PR DESCRIPTION
**Pull request by adrianlop**

### CODE REVIEW

**Review by jeevatkm — COMMENTED** [review]
@adrianlop Thank you for your PR 😄 

I have gone through the PR. It's more or less same, have in the mind. Also, register methods we have to simplify it.

There are most important things to address for this PR or before this PR-

* We have to provide access to `collector` instance for health check controller action!!! Since aah controller instances are stateless by nature, I think `func` based parameter resolve support would solve it also opens up more avenues.

* As of today aah controller registry has support for controllers from an application only. We have to add support for anywhere such as from libraries too.

**Comment by adrianlop** [comment]
@jeevatkm this is working nicely now on our Aah APIs!!!!
thank you very much for the help.
can you please approve this PR in the meantime? I'd like to have this on master, and then work later on another PR so that we can register actions with parameters.
cheers.

**Comment by jeevatkm** [comment]
@adrianlop we can merge it but it needs some work on register func(s). Let me do an update this PR so you can review then we can merge it.

**Comment by jeevatkm** [comment]
@adrianlop I have updated implementation, please have a look. Then we can merge it.

**Comment by adrianlop** [comment]
nice one @jeevatkm thank you very much.
I can't do a GH Review since I created the PR, but changes are good so happy to merge if you like.

**Review by jeevatkm — APPROVED** [review]

**Pull request merged**
